// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using wypożyczalnia_samochodów.Entites;

namespace wypożyczalnia_samochodów.Migrations
{
    [DbContext(typeof(WypozyczalniaDbContext))]
    [Migration("20221109213100_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.1");

            modelBuilder.Entity("wypożyczalnia_samochodów.Entites.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Class")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Combustion")
                        .HasColumnType("real");

                    b.Property<string>("Localization")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WypozyczalniaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WypozyczalniaId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("wypożyczalnia_samochodów.Entites.Wypozyczalnia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Wypozyczalnie");
                });

            modelBuilder.Entity("wypożyczalnia_samochodów.Entites.Car", b =>
                {
                    b.HasOne("wypożyczalnia_samochodów.Entites.Wypozyczalnia", "Wypozyczalnia")
                        .WithMany("Cars")
                        .HasForeignKey("WypozyczalniaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wypozyczalnia");
                });

            modelBuilder.Entity("wypożyczalnia_samochodów.Entites.Wypozyczalnia", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
